name: Build Appium Portable

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install npm packages
        run: npm ci
      - name: Build appium portable
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: appium
          path: dist